server:
  port: 10020

spring:
  application:
    name: spring-boot-redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 10
      max-idle: 10
      min-idle: 5
