server:
  port: 10022
spring:
  application:
    name: spring-boot-freemarker
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
