server:
  port: 10000
# 应用名称
spring:
  application:
    name: spring-boot-elasticsearch
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization.write-dates-as-timestamps: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jeespring-boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  elasticsearch:
    rest:
      uris: http://192.168.19.10:9200
mybatis:
  type-aliases-package: com.jeespring.elasticsearch.entity  # 定义所有操作类的别名所在包
  mapper-locations: classpath:/mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  pagehelper.page-size-zero: true


