spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-boot?characterEncoding=utf-8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.jeespring.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 10016